[project]
name = "smart-arweave-parser"
authors = ["Your Name <your.email@example.com>"]
description = "A Clarity smart contract for parsing and interacting with Arweave data transactions"
telemetry = false
requirements = []
[contracts.arweave_parser]
path = "contracts/arweave-parser.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
